// "use client";
// utils
import React, { StrictMode } from "react";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
// hooks
// components
import Login from "../components/Login";
import Main from "../components/navigation/main";
import Header from "../components/navigation/header";
import Footer from "../components/navigation/footer";
// styles
import { Noto_Sans_TC } from "next/font/google";
import classnames from "classnames";
import "./globals.css";

const inter = Noto_Sans_TC({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GDSC NCCU Member Website",
  description: "Generated by create next app",
  manifest: "./manifest.json",
  icons: {
    icon: "./logo.png",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const isLogin = useAppSelector((state) => state.User.isLogin);
  // const pathname = usePathname();

  const session = await getServerSession();

  return (
    <html lang="en">
      <StrictMode>
        <body className={inter.className}>
          {" "}
          <div
            className={classnames(
              "flex w-full h-full min-h-screen flex-col items-center justify-between",
              "bg-base-100 relative",
            )}
          >
            {session && (
              <>
                <Header />
                <Main>{children}</Main>
                <Footer />
              </>
            )}
            {!session && (
              <>
                <Login />
              </>
            )}
          </div>
        </body>
      </StrictMode>
    </html>
  );
}
