"use client";
// utils
import type { ReactElement, ReactNode } from "react";
import type { NextPage, Metadata } from "next";
import type { AppProps } from "next/app";
import { StrictMode } from "react";
// hooks
import { useUnitedResize } from "../hooks";
import { useRef } from "react";
import { usePathname } from "next/navigation";
// components
import Header from "../components/navigation/header";
import Footer from "../components/navigation/footer";
// styles
import { Inter } from "next/font/google";
import classnames from "classnames";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "GDSC NCCU Member Website",
//   description: "Generated by create next app",
//   icons: {
//     icon: "./logo.png",
//   },
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const isLogin = useAppSelector((state) => state.User.isLogin);
  const pathname = usePathname();

  return (
    <html lang="en">
      <StrictMode>
        <body className={inter.className}>
          {" "}
          <div
            className={classnames(
              "flex w-full min-h-screen flex-col items-center justify-between",
              "transition-colors duration-200 ease-in-out",
              { "bg-base-100 text-base-content": pathname !== "/profile" },
              { "bg-base-200 text-base-content": pathname === "/profile" },
            )}
          >
            <Header />
            <main className="border-4 border-blue-500 grow w-full">
              {children}
            </main>
            {/* {isBreak ? <Footer /> : ""} */}
          </div>
        </body>
      </StrictMode>
    </html>
  );
}
